spring:
  config:
    import:
      - "optional:nacos:${spring.application.name}.properties?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}&refreshEnabled=true"
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      config:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        import-check:
          enabled: true
      discovery:
        enabled: true
        register-enabled: true
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
